#!/usr/bin/env bash

container_check() {
    pass
}

config_check() {
    pass
}

up() {
    lxc init ubuntu: $1
    lxc config set $1 user.user-data - < "$1.yaml"
    lxc start $1
}

ssh() {
    lxc exec $1 bash
}

halt() {
    lxc stop $1
}

destroy() {
    lxc delete $1
}
