# -*- mode: ruby -*-
# vi: set ft=ruby :


nodes = [
  { hostname:  "master.sql.cluster",
    ip:        "192.168.56.50"
  },
  {
    hostname:  "node1.sql.cluster",
    ip:        "192.168.56.51"
  },
  {
    hostname:  "node2.sql.cluster",
    ip:        "192.168.56.52"
  }
]

Vagrant.configure(2) do |config|
  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
  end
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = "ubuntu/xenial64"
      nodeconfig.vm.hostname = node[:hostname]
      nodeconfig.vm.network :private_network, ip: node[:ip]
      nodeconfig.vm.synced_folder ".", "/vagrant", disabled: true
      nodeconfig.vm.provider :virtualbox do |v|
        v.name = node[:hostname]
        v.memory = 1024
      end
    end
  end
end
