ubuntu_box = "ubuntu/xenial64"

local_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip

nodes = %w(
    elliot
    tyson
)

Vagrant.configure(2) do |config|

  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  nodes.each_with_index do |node, i|
    config.vm.define node do |nodeconf|

      nodeconf.vm.hostname = node
      nodeconf.vm.box = ubuntu_box
      nodeconf.vm.network :private_network, ip: "172.17.17.#{i+100}"

      nodeconf.vm.synced_folder ".", "/vagrant", disabled: true

      nodeconf.vm.provision :shell, inline: "command -v python || (apt update && apt install -y python-minimal)"
      nodeconf.vm.provision :shell, inline: "echo #{local_key} >> /home/ubuntu/.ssh/authorized_keys"

      nodeconf.vm.provider :virtualbox do |vbox|
        vbox.name = "wire.#{node}"
      end
    end
  end
end
