vagrant_box = "ubuntu/xenial64"

nodes = %w(
    data
    web1
    web2
    lb
)

Vagrant.configure(2) do |config|

  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
  else
      abort("Vagrant Hostmanager required, https://github.com/devopsgroup-io/vagrant-hostmanager")
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  nodes.each_with_index do |node, index|
    config.vm.define node do |nodeconf|
      nodeconf.vm.hostname = node
      nodeconf.vm.box = vagrant_box
      nodeconf.vm.network :private_network, ip: "192.168.56.21#{index}"

      nodeconf.vm.synced_folder ".", "/vagrant", disabled: true

      nodeconf.vm.provision :shell, inline: "apt update && apt install -y python-minimal"

      nodeconf.vm.provision :ansible do |a|
        a.playbook = "#{node}.yml"
      end

      # Optional shell provisioner
      #nodeconf.vm.synced_folder "shell/#{node}", "/#{node}"
      #nodeconf.vm.provision :shell, path: "shell/#{node}/#{node}.sh"

      if node == "lb"
        nodeconf.hostmanager.aliases = %w(blog.example.com shop.example.com forum.example.com)
      end

      nodeconf.vm.provider :virtualbox do |vbox|
        vbox.name   = "vagrant.#{node}"
        vbox.memory = 512
        vbox.cpus = 1
      end
    end
  end
end
