require 'etc'

project_name = "dreadnought"
username     = Etc.getlogin
ssh_pub_key  = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip

vagrant_box = "ubuntu/xenial64"

nodes = %w(
    data
    web1
    web2
    lb
)

Vagrant.configure(2) do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
#  config.vbguest.auto_update = false

  nodes.each_with_index do |node, index|
    config.vm.define node do |nodeconf|
      nodeconf.vm.hostname = node
      nodeconf.vm.box = vagrant_box
      nodeconf.vm.network :private_network, ip: "192.168.56.21#{index}"

      nodeconf.vm.synced_folder ".", "/vagrant", disabled: true # Disable default shared folder
      nodeconf.vm.synced_folder "#{node}/", "/#{node}"

      nodeconf.vm.provision :shell, path: "user.sh", args: [username, ssh_pub_key]
      nodeconf.vm.provision :shell, path: "#{node}/#{node}.sh"

      if node == "lb"
        nodeconf.hostmanager.aliases = %w(blog.example.com shop.example.com forum.example.com)
      end

      nodeconf.vm.provider :virtualbox do |vbox|
        vbox.name   = "#{project_name}.#{node}"
        vbox.memory = 1024
      end
    end
  end
end
