ubuntu_box = 'ubuntu/xenial64'

nodes = 5

Vagrant.configure(2) do |config|

  if Vagrant.has_plugin?('vagrant-hostmanager')
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
  end

  if Vagrant.has_plugin?('vagrant-vbguest')
    config.vbguest.auto_update = false
  end

  1.upto(nodes) do |i|
    config.vm.define "node#{i}" do |nodeconf|

      nodeconf.vm.hostname = "node#{i}"
      nodeconf.vm.box = ubuntu_box
      nodeconf.vm.network :private_network, ip: "172.37.17.#{i+20}"

      nodeconf.vm.synced_folder '.', '/vagrant', disabled: true

      nodeconf.vm.provision :shell, inline: 'apt update && apt install -y python-minimal'

      nodeconf.vm.provision :ansible do |a|
        if i == 1 or i == 2 
          a.playbook = "balancer.yml"
        else
          a.playbook = "node.yml"
        end

        a.inventory_path = "local/inventory"
      end

      nodeconf.vm.provider :virtualbox do |vbox|
        vbox.name = "bed.node#{i}"
        vbox.linked_clone = true
      end
    end
  end
end
