centos_box = 'centos/7'
ubuntu_box = "ubuntu/xenial64"

nodes = %w(
    db
    web1
    web2
    lb
    master
)

Vagrant.configure(2) do |config|

  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
  else
      abort("Vagrant Hostmanager required, https://github.com/devopsgroup-io/vagrant-hostmanager")
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  nodes.each_with_index do |node, i|
    config.vm.define node do |nodeconf|

      nodeconf.vm.hostname = node

      nodeconf.vm.box = ubuntu_box

      nodeconf.vm.network :private_network, ip: "172.17.99.#{i+100}"

      nodeconf.vm.synced_folder ".", "/vagrant", disabled: true
    
      if node == 'master'
          nodeconf.vm.provision :shell, inline: "curl -L https://bootstrap.saltstack.com | sudo sh -s -- -M"
          nodeconf.vm.provision :shell, inline: "sudo salt-key -y -A"
          nodeconf.vm.synced_folder 'master/master.d/', '/etc/salt/master.d/', type: 'virtualbox', owner: 'root', group: 'root'
          nodeconf.vm.synced_folder 'master/minion.d/', '/etc/salt/minion.d/', type: 'virtualbox', owner: 'root', group: 'root'
          nodeconf.vm.synced_folder 'master/pillar/', '/srv/pillar/', type: 'virtualbox', owner: 'root', group: 'root'
          nodeconf.vm.synced_folder 'master/salt/', '/srv/salt/', type: 'virtualbox', owner: 'root', group: 'root'
      else
          nodeconf.vm.provision :shell, inline: "curl -L https://bootstrap.saltstack.com | sudo sh"
          nodeconf.vm.synced_folder 'minion/minion.d/', '/etc/salt/minion.d/', type: 'virtualbox', owner: 'root', group: 'root'
      end

      nodeconf.vm.provider :virtualbox do |vbox|
        if node == 'master'
            vbox.memory = 2048
        end
        vbox.name = "vagrant.#{node}"
      end
    end
  end
end
