centos_box = 'centos/7'
ubuntu_box = "ubuntu/xenial64"

nodes = %w(
    db
    web1
    web2
    lb
    master
)

Vagrant.configure(2) do |config|

  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
  else
      abort("Vagrant Hostmanager required, https://github.com/devopsgroup-io/vagrant-hostmanager")
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  nodes.each_with_index do |node, i|
    config.vm.define node do |nodeconf|

      nodeconf.vm.hostname = node

      nodeconf.vm.box = ubuntu_box

      nodeconf.vm.network :private_network, ip: "172.17.17.#{i+100}"

      nodeconf.vm.synced_folder ".", "/vagrant", disabled: true
    
      if node == 'master'
        nodeconf.vm.provision :shell, path: "master/shell/boot.sh"

        sync_folders = [
          { host: 'master/master.d/', node: '/etc/salt/master.d' },
          { host: 'master/minion.d/', node: '/etc/salt/minion.d' },
          { host: 'master/pillar/',   node: '/srv/pillar/' },
          { host: 'master/salt/',     node: '/srv/salt/' }
        ]

        sync_folders.each do |folder|
          nodeconf.vm.synced_folder folder[:host], folder[:node], type: 'virtualbox', owner: 'root', group: 'root'
        end
      else
          nodeconf.vm.provision :shell, path: "minion/shell/boot.sh"
          nodeconf.vm.synced_folder 'minion/minion.d/', '/etc/salt/minion.d/', type: 'virtualbox', owner: 'root', group: 'root'
      end

      nodeconf.vm.provider :virtualbox do |vbox|
        if node == 'master'
            vbox.memory = 2048
        end
        vbox.name = "#{node}.salt"
      end
    end
  end
end
