ubuntu_box = "ubuntu/xenial64"

nodes = %w(
    burger    
    pizza
    sushi
    tacos
)

Vagrant.configure(2) do |config|

  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  nodes.each_with_index do |node, i|
    config.vm.define node do |nodeconf|

      nodeconf.vm.hostname = node

      nodeconf.vm.box = ubuntu_box

      nodeconf.vm.network :private_network, ip: "172.37.17.#{i+100}"

      nodeconf.vm.synced_folder ".", "/vagrant", disabled: true

      nodeconf.vm.provision :shell, path: "common/boot.sh"

      if node == "sushi"
        nodeconf.vm.provision :shell, path: "master/boot.sh"
      else
        nodeconf.vm.provision :shell, path: "nodes/boot.sh"
      end

      nodeconf.vm.provider :virtualbox do |vbox|
        vbox.name = "kube.#{node}"
        vbox.linked_clone = true
        if node == "sushi"
          vbox.memory = 204
        end
      end
    end
  end
end
