nodes = %w(
  web
  data
)

Vagrant.configure(2) do |config|

  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
  else
    abort("Vagrant Hostmanager required")
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  nodes.each_with_index do |node, index|
    config.vm.define node do |nodeconfig|
      nodeconfig.vm.box = "ubuntu/xenial64"
      nodeconfig.vm.hostname = node
      nodeconfig.vm.network :private_network, ip: "192.168.56.22#{index}"
      nodeconfig.vm.synced_folder ".", "/vagrant", disabled: true
    end
  end
end
