ubuntu_box = "ubuntu/xenial64"
centos_box = "centos/7"

nodes = %w(
    master
    worker1
    worker2
    worker3
    client1
    client2
)

Vagrant.configure(2) do |config|

  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
  else
      abort("Vagrant Hostmanager required, https://github.com/devopsgroup-io/vagrant-hostmanager")
  end

  nodes.each do |node|
    config.vm.define node do |nodeconf|
      nodeconf.vm.hostname = node
      nodeconf.vm.box = ubuntu_box
      nodeconf.vm.network :private_network, type: "dhcp"

      nodeconf.vm.synced_folder ".", "/vagrant", disabled: true

      #nodeconf.vm.provision :puppet do |p|
      #  p.manifests_path = "provision/manifests"
      #  p.module_path = "provision/modules"
      #end

      nodeconf.vm.provider :virtualbox do |vbox|
        if node == "master"
            vbox.memory = 8192
        else
            vbox.memory = 2048
        end
        vbox.name = "hadoop.#{node}"
      end
    end
  end
end
