ubuntu_box = "ubuntu/xenial64"
centos_box = "centos/7"

nodes = %w(
    data
    slave
    web1
    web2
    elk
    lb
)

Vagrant.configure(2) do |config|

  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
  else
      abort("Vagrant Hostmanager required, https://github.com/devopsgroup-io/vagrant-hostmanager")
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  nodes.each do |node|
    config.vm.define node do |nodeconf|

      nodeconf.vm.hostname = node

      if node == "elk"
        nodeconf.vm.box = centos_box
      else
        nodeconf.vm.box = ubuntu_box
      end

      nodeconf.vm.network :private_network, type: "dhcp"

      nodeconf.vm.synced_folder ".", "/vagrant", disabled: true

      unless node == "elk"
        nodeconf.vm.provision :shell, inline: "apt update && apt install -y python-minimal"
      end

      nodeconf.vm.provision :ansible do |a|
        a.playbook = "#{node}.yml"
        a.inventory_path = "local/inventory"
      end

      # Optional shell provisioner
      #nodeconf.vm.synced_folder "shell/#{node}", "/#{node}"
      #nodeconf.vm.provision :shell, path: "shell/#{node}/#{node}.sh"

      if node == "lb"
        nodeconf.hostmanager.aliases = %w(
          blog.example.com
          shop.example.com
          forum.example.com
          elk.example.com
        )
      end

      nodeconf.vm.provider :virtualbox do |vbox|
        if node == "elk"
            vbox.memory = 2048
        end
        vbox.name = "vagrant.#{node}"
      end
    end
  end
end
