# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network :private_network, ip: "192.168.56.190"
  config.vm.provision :shell, path: 'space.sh'

  config.vm.provider "virtualbox" do |vb|
    vb.name = "spacebox"
    vb.memory = 1024
  end
end
