Vagrant.configure(2) do |config|

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.hostname = "varnish"
  config.vm.box = "centos/7"
  config.vm.network :private_network, type: "dhcp"
  config.vm.provision :shell, path: "varnish.sh"
end
